on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
permissions:
  pull-requests: write

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
      - name: PR Bot
        uses: langchain4j/pr-bot@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          GOOGLE_AI_GEMINI_API_KEY: ${{ secrets.GOOGLE_AI_GEMINI_API_KEY }}
